name: fresh_fruit
description: 530PM Fruits project

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.2
  http: ^0.13.3


  sqflite: 2.0.1
  localstorage: 4.0.1+2
  image_gallery_saver: ^2.0.2
  geolocator: ^9.0.2


  google_geocoding_api: ^1.3.0
  cloud_firestore: 4.4.5
  firebase_core: 2.14.0
  firebase_auth: 4.6.3
  firebase_crashlytics: ^3.0.17
  firebase_analytics: ^10.4.1
  firebase_dynamic_links: ^5.0.16
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^15.0.0

  provider: 6.0.5
  package_info_plus: 4.0.2
  connectivity_plus: ^2.3.6+1
  flex_seed_scheme: ^1.0.0
  custom_refresh_indicator: ^1.2.1
  carousel_slider: ^4.0.0
  logger: ^1.1.0
  cached_network_image: ^3.2.2
  shimmer: ^2.0.0
  animated_bottom_navigation_bar: ^1.2.0
  auto_size_text: ^3.0.0
  flutter_svg: ^1.0.3
  easy_rich_text: 1.1.0
  flutter_html: ^3.0.0-alpha.6
  intl: ^0.17.0
  page_route_animator: ^1.0.3
  flutter_time_picker_spinner: ^2.0.0
  open_store: ^0.5.0
  flutter_secure_storage: 8.0.0
  equatable: 2.0.5
  flutter_easyloading: 3.0.5
  animated_text_kit: ^4.2.2
  figma_squircle: 0.5.3
  pin_code_text_field: ^1.8.0


dev_dependencies:
  cupertino_icons: ^1.0.2

  flutter_driver:
    sdk: flutter

  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/bottom_bar/
    - assets/config/
