name: fresh_fruit
description: 530PM Fruits project

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  cupertino_icons: ^1.0.2

  sqflite: 2.0.1
  localstorage: 4.0.1+2


  cloud_firestore: 4.4.5
  firebase_core: 2.14.0
  firebase_auth: 4.6.3
  firebase_crashlytics: ^3.0.17
  firebase_analytics: ^10.4.1
  firebase_dynamic_links: ^5.0.16

  provider: 6.0.5
  package_info_plus: 4.0.2
  shared_preferences: ^2.0.15
  connectivity_plus: ^2.3.6+1
  flex_seed_scheme: ^1.0.0
  custom_refresh_indicator: ^1.2.1
  carousel_slider: ^4.0.0
  logger: ^1.1.0
  cached_network_image: ^3.2.2
  shimmer: ^2.0.0
  animated_bottom_navigation_bar: ^1.2.0
  auto_size_text: ^3.0.0
  flutter_svg: ^1.0.3
  easy_rich_text: 1.1.0
  flutter_html: ^3.0.0-alpha.6
  intl: ^0.17.0
  page_route_animator: ^1.0.3
  syncfusion_flutter_datepicker: "20.4.44"
  open_store: ^0.5.0

  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/bottom_bar/
    - assets/config/
